# Generated by Django 4.1.7 on 2023-02-16 06:07

import ckeditor.fields
from django.db import migrations, models
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('92b22b6f-4631-4831-b41a-c46a7f23fa0c'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, null=True)),
                ('last_name', models.CharField(max_length=300)),
                ('age', models.IntegerField()),
                ('company', models.CharField(choices=[('Баткен Stream', 'Баткен Stream'), ('Яндекс', 'Яндекс'), ('Байбол', 'Байбол'), ('Алга', 'Алга'), ('Бат такси', 'Бат такси')], max_length=100)),
                ('transport', models.CharField(max_length=100)),
                ('tr_number', models.CharField(default='xx xx xx x', max_length=20)),
                ('direction', models.CharField(choices=[('BAT_BUJ', 'Баткен-Бужум'), ('BAT_SAM', 'Баткен-Самаркандек'), ('SAM_AT', 'Самаркандек-Ак-Татыр'), ('BAT_LEY', 'Баткен-Лейлек'), ('ISF_KAD', 'Исфана-Кадамжай'), ('KYZ_KAD', 'Кызыл_Кыя-Кадамжай')], max_length=300)),
                ('places', models.IntegerField()),
                ('working_days', multiselectfield.db.fields.MultiSelectField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверть', 'Четверть'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота')], max_length=400)),
                ('description', ckeditor.fields.RichTextField(max_length=500)),
                ('url_instagram', models.URLField(blank=True)),
                ('date_creat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
