# Generated by Django 4.1.7 on 2023-02-16 06:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9c45205b-5dad-49fc-8a31-55b09232d5b5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
