# Generated by Django 4.1.7 on 2023-02-16 07:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_workers_photo_alter_workers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e83239b2-ca95-4c6c-ad89-b4bda80a3e88'), editable=False, primary_key=True, serialize=False),
        ),
    ]
