# Generated by Django 4.1.7 on 2023-02-16 07:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_workers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='id',
            field=models.UUIDField(blank=True, default=uuid.UUID('bf3a36cf-333a-4302-aa8c-c3471160334c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
