# Generated by Django 4.1.7 on 2023-02-16 07:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_workers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3c5aa4d6-d3ad-4fda-84bf-13b4ebd80c37'), editable=False, primary_key=True, serialize=False),
        ),
    ]
