# Generated by Django 4.1.7 on 2023-02-21 10:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_workers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='id',
            field=models.UUIDField(default=uuid.UUID('eec6f22f-239a-475f-ae10-214340c370fe'), editable=False, primary_key=True, serialize=False),
        ),
    ]
